# 프로그래머스 강의(자바 입문) - 13. 내부 및 익명 클래스, 예외 처리

# 목차
- [내부 클래스](#내부-클래스)
- [익명 클래스](#익명-클래스)
- [예외 처리](#예외-처리)

<br>

# 내부 클래스

> `내부 클래스` : 클래스 안에 선언된 클래스

## 내부 클래스 1 : 중첩 클래스 또는 인스턴스 클래스
```java
public class InnerExam1 {
    class Cal{
        int value = 0;
        public void plus(){
            value++;
        }
    }

    public static void main(String[] args) {
        InnerExam1 t = new InnerExam1();

        InnerExam1.Cal cal = t.new Cal();

        cal.plus();
        System.out.println(cal.value);  // 1
    }
}
```

내부 클래스 `Cal`를 사용하기 위해서 먼저 외부에 있는 클래스 `InnerExam1`을 생성해준다. <br>
그 이후 타입은 `클래스타입.내부타입`으로 선언해주고, 외부 클래스 객체를 이용해 생성해준다.

<br>

## 내부 클래스 2 : 정적 중첩 클래스 또는 스태틱 클래스
```java
public class InnerExam2 {
    static class Cal{
        int value = 0;
        public void plus(){
            value++;
        }
    }

    public static void main(String[] args) {
        InnerExam2.Cal cal = new InnerExam2.Cal();

        cal.plus();
        System.out.println(cal.value);  // 1
    }
}
```

- `스태틱 클래스`이기 때문에 외부에 있는 클래스를 생성할 필요 없이 외부 클래스를 통해 바로 호출해주면 된다.

<br>

## 내부 클래스 3 : 지역 중첩 클래스 또는 지역 클래스
```java
public class InnerExam3 {
    public void exec(){
        class Cal{
            int value = 0;
            public void plus(){
                value++;
            }
        }

        Cal cal = new Cal();
        cal.plus();
        System.out.println(cal.value);
    }

    public static void main(String[] args) {
        InnerExam3 t = new InnerExam3();

        t.exec();   // 1
    }
}
```

이렇게 메소드 안에 정의되는 클래스도 `내부 클래스`에 해당되고, 외부 클래스를 통해 해당 메소드를 불러오면 메소드 안에 있는 내용처럼 내부 클래스가 동작된다.

<br>

---

<br>

# 익명 클래스

앞서 내부 클래스의 3가지 종류를 살펴보았고, 마지막 하나의 내부 클래스의 종류인 `익명 클래스`를 알아보자.

익명 클래스를 쉽게 알기 위해 먼저 추상 클래스를 사용하는 기본적인 형태를 보자.

## 기본적인 형태

### 추상 클래스 
```java
public abstract class Action {
    public abstract void exec();
}
```

### 자식 클래스
```java
public class MyAction extends Action {
    @Override
    public void exec() {
        System.out.println("exec");
    }
}
```

### 자식 클래스 사용
```java
public class ActionExam {
    public static void main(String[] args) {

        Action action = new MyAction();
        action.exec();  // exec
    }
}
```

이게 추상클래스를 사용하는 기본적인 형태지만 익명클래스는 `자식 클래스(MyAction)`을 만들지 않고 `ActionExam`에서 **Action을 상속**받은 `익명클래스`를 만들어서 사용하게 된다.

## 익명클래스
```java
public class ActionExam {
    public static void main(String[] args) {
        Action action = new Action(){
            @Override
            public void exec() {
                System.out.println("exec");
            }
        };
        action.exec();  // exec
    }
}
```

기본적인 형태로 사용하는 것과 똑같이 메소드를 사용하는 것을 알 수 있다. <br>
생성자 다음에 중괄호 블록은 **생성자 이름에 해당하는 클래스를 상속**받아 이름없는 객체를 만드는 것을 의미한다. <br>
이 중괄호 블록에서는 메소드를 구현하거나 추가할 수 있다.

> 사용하는 이유 : 추상(부모) 클래스를 상속받는 클래스를 굳이 만들어낼 필요가 없을 때 사용한다. 즉, 액션을 상속받는 클래스(자식 클래스)가 해당 클래스에서만 사용이 되는 경우에 사용한다.

<br>

---

<br>

# 예외 처리

> `예외` : 프로그램이 실행 중에 예기치 못한 사건

## Exception
만약 아래와 같은 코드가 있다고 가정해보고 결과를 보자

### 예외 발생 코드
```java
public class ExceptionExam {
    public static void main(String[] args) {
        int i = 10;
        int j = 0;
        int k = i/j;

        System.out.println("end");  // 출력 안 됨
    }
}
```
<p align=center>
<img width="673" alt="스크린샷 2024-03-05 12 48 04" src="https://github.com/hamsangjin/TIL/assets/103736614/cc03e739-54a1-4cc6-ac73-de28fa5517ae">
</p>

자바는 정수로 0으로 나눌 때 예외를 발생시키므로 5번째 줄에서 `ArithmeticException`라는 예외가 발생해 그 아래 코드는 실행되지 않는 걸 볼 수 있다.<br>

<br>

### 예외 처리 문법
자바는 위와 같이 예외가 발생했을 때 예외를 처리하는 문법을 제공해준다.
```java
try{
  // 수행 코드이며, 예외 발생 가능성이 있는 코드
} catch(예외클래스 변수명){
  // 예외가 발생했을 때 실행할 코드
} finally{
  // 생략 가능하며, 예외 발생 여부에 상관없이 반드시 실행되는 블록
}
```

<br>

### 예외 처리 코드
이제 예외 처리 문법을 이용해 앞서 발생한 예외를 처리해주자
```java
public class ExceptionExam {
    public static void main(String[] args) {
        int i = 10;
        int j = 0;

        try {
            int k = i / j;
        } catch(ArithmeticException e){
            System.out.println("0으로 나눌 수 없습니다." + e.toString());
        } finally {
            System.out.println("오류가 발생했든 안 했든 무조건 실행");
        }
        System.out.println("end");
    }
}
```
<p align=center>
<img width="487" alt="스크린샷 2024-03-05 13 45 08" src="https://github.com/hamsangjin/TIL/assets/103736614/cc3243d9-a35e-43c3-9966-c3f09f82abcb">
</p>

- 여기서 오류 변수 `e`에서 `toString` 메소드를 이용해 출력하면, 발생한 오류 정보를 알 수 있다.
- 만약 `try` 블록에서 여러 종류의 예외가 발생한다면 `catch` 블록을 여러개 두어 예외를 처리할 수 있고 또, 예외 클래스의 가장 상위 클래스인 `Exception` 클래스를 명시해 하나의 `catch` 블록에서 여러 종류의 예외를 한 번에 처리할 수 있다.

<br>

## Throws

> `Throws` : 만약 메소드를 실행하다가 오류가 발생했으면, 메소드 내에서 수행하다가 발생되는 오류를 메소드 내에서 처리하지 않고, 이 메소드를 호출한 쪽에서 처리할 수 있도록 오류를 떠넘기는 것.
> `Throws` 역시 `,`를 이용해 여러 개의 오류를 처리할 수 있고, `Exception`으로도 모든 예외 처리가 가능하다.

```java
public class ExceptionExam2 {
    public static void main(String[] args) {
        int i = 10;
        int j = 0;
        try {
            int k = divide(i, j);
        } catch (ArithmeticException e){
            System.out.println(e.toString());
        }
    }

    public static int divide(int i, int j) throws ArithmeticException{
        return i / j;
    }
}
```

<br>

## Exception 발생시키기

이번엔 강제로 오류를 발생시키는 `Throw`에 대해서 알아보자. <br>

나눗셈을 할 때 **나누는 수가 0인 경우**엔 오류가 발생하니, 만약 **나누는 수가 0이면 예외를 발생**하게 해보자.
```java
public class ExceptionExam3 {
    public static void main(String[] args) {
        int i = 10;
        int j = 0;
        try {
            int k = divide(i, j);
        }catch (IllegalArgumentException e){
            System.out.println(e.toString());
        }
    }

    public static int divide(int i, int j) throws IllegalArgumentException{
        if(j == 0) {
            throw new IllegalArgumentException("0으로 나눌 수 없습니다.");
        }
        return i / j;
    }
}
```

- 출력 결과 : `java.lang.IllegalArgumentException: 0으로 나눌 수 없습니다.`

`j == 0`이라면, 발생시키고 싶은 `Exception 객체`를 생성한 후, `throw`로 해당 Exception을 발생시킨 것이다.

<br>

## 사용자 정의 Exception

### Exception을 정의하는 법
```java
public class 클래스명 extends Exception{
  ...
}
```
- Exception이나 Exception의 자식을 상속받아 만들어진 클래스이며, 클래스의 이름만으로 어떤 오류가 발생했는지 알려주어 코드의 직관성을 높이는 것이 목표다.

### 사용자 정의 Exception
```java
public class BizException extends RuntimeException{

    // 문자열로 만들어진 오류메시지
    public BizException(String msg) {
        super(msg);
    }

    // 실제 발생할 오류
    public BizException(Exception ex) {
        super(ex);
    }
}
```

### 사용자 정의 Exception 클래스를 사용하는 메소드
```java
public class BizService {
    public void bizMethod(int i) throws BizException{
        System.out.println("비즈니스 메소드 시작");

        if(i < 0){
            throw new BizException("매개변수 i는 0이상이어야 합니다.");
        }

        System.out.println("비즈니스 메소드 끝");
    }
}

```

### 메소드 사용
```java
public class BizExam {
    public static void main(String[] args) {
        BizService bizService = new BizService();

        bizService.bizMethod(5);
        try{
            bizService.bizMethod(-3);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
}

```

### 출력 결과
<p align=center>
<img width="401" alt="스크린샷 2024-03-05 15 42 47" src="https://github.com/hamsangjin/TIL/assets/103736614/4c77e99a-8a08-43e3-82ea-85c5e0f42c2c">
</p>
